// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Util.proto

// Protobuf Java Version: 4.26.0-rc2
package org.example.java_out;

public interface DateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.Date)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 year = 1;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 day = 3;</code>
   * @return The day.
   */
  int getDay();
}
