// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoGames.proto

// Protobuf Java Version: 4.26.0-rc2
package org.example.java_out;

public interface VideoGameLibraryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.VideoGameLibrary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  java.util.List<org.example.java_out.VideoGame> 
      getGameList();
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  org.example.java_out.VideoGame getGame(int index);
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  int getGameCount();
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  java.util.List<? extends org.example.java_out.VideoGameOrBuilder> 
      getGameOrBuilderList();
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  org.example.java_out.VideoGameOrBuilder getGameOrBuilder(
      int index);
}
