// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoGames.proto

// Protobuf Java Version: 4.26.0-rc2
package org.example.java_out;

/**
 * Protobuf type {@code org.example.VideoGame}
 */
public final class VideoGame extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.example.VideoGame)
    VideoGameOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "-rc2",
      VideoGame.class.getName());
  }
  // Use VideoGame.newBuilder() to construct.
  private VideoGame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VideoGame() {
    name_ = "";
    type_ = 0;
    matchPlayed_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.java_out.VideoGame.class, org.example.java_out.VideoGame.Builder.class);
  }

  /**
   * Protobuf enum {@code org.example.VideoGame.GameType}
   */
  public enum GameType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GENERIC = 0;</code>
     */
    GENERIC(0),
    /**
     * <code>SPORTS = 1;</code>
     */
    SPORTS(1),
    /**
     * <code>ADVENTURE = 2;</code>
     */
    ADVENTURE(2),
    /**
     * <code>CRAFTING = 3;</code>
     */
    CRAFTING(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "-rc2",
        GameType.class.getName());
    }
    /**
     * <code>GENERIC = 0;</code>
     */
    public static final int GENERIC_VALUE = 0;
    /**
     * <code>SPORTS = 1;</code>
     */
    public static final int SPORTS_VALUE = 1;
    /**
     * <code>ADVENTURE = 2;</code>
     */
    public static final int ADVENTURE_VALUE = 2;
    /**
     * <code>CRAFTING = 3;</code>
     */
    public static final int CRAFTING_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GameType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GameType forNumber(int value) {
      switch (value) {
        case 0: return GENERIC;
        case 1: return SPORTS;
        case 2: return ADVENTURE;
        case 3: return CRAFTING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GameType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameType>() {
            public GameType findValueByNumber(int number) {
              return GameType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.example.java_out.VideoGame.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameType[] VALUES = values();

    public static GameType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GameType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.example.VideoGame.GameType)
  }

  public interface MatchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.VideoGame.Match)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.example.Date matchDate = 1;</code>
     * @return Whether the matchDate field is set.
     */
    boolean hasMatchDate();
    /**
     * <code>.org.example.Date matchDate = 1;</code>
     * @return The matchDate.
     */
    org.example.java_out.Date getMatchDate();
    /**
     * <code>.org.example.Date matchDate = 1;</code>
     */
    org.example.java_out.DateOrBuilder getMatchDateOrBuilder();

    /**
     * <code>optional int32 matchDuration = 2;</code>
     * @return Whether the matchDuration field is set.
     */
    boolean hasMatchDuration();
    /**
     * <code>optional int32 matchDuration = 2;</code>
     * @return The matchDuration.
     */
    int getMatchDuration();
  }
  /**
   * Protobuf type {@code org.example.VideoGame.Match}
   */
  public static final class Match extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.VideoGame.Match)
      MatchOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "-rc2",
        Match.class.getName());
    }
    // Use Match.newBuilder() to construct.
    private Match(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Match() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_Match_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_Match_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.java_out.VideoGame.Match.class, org.example.java_out.VideoGame.Match.Builder.class);
    }

    private int bitField0_;
    public static final int MATCHDATE_FIELD_NUMBER = 1;
    private org.example.java_out.Date matchDate_;
    /**
     * <code>.org.example.Date matchDate = 1;</code>
     * @return Whether the matchDate field is set.
     */
    @java.lang.Override
    public boolean hasMatchDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.org.example.Date matchDate = 1;</code>
     * @return The matchDate.
     */
    @java.lang.Override
    public org.example.java_out.Date getMatchDate() {
      return matchDate_ == null ? org.example.java_out.Date.getDefaultInstance() : matchDate_;
    }
    /**
     * <code>.org.example.Date matchDate = 1;</code>
     */
    @java.lang.Override
    public org.example.java_out.DateOrBuilder getMatchDateOrBuilder() {
      return matchDate_ == null ? org.example.java_out.Date.getDefaultInstance() : matchDate_;
    }

    public static final int MATCHDURATION_FIELD_NUMBER = 2;
    private int matchDuration_ = 0;
    /**
     * <code>optional int32 matchDuration = 2;</code>
     * @return Whether the matchDuration field is set.
     */
    @java.lang.Override
    public boolean hasMatchDuration() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 matchDuration = 2;</code>
     * @return The matchDuration.
     */
    @java.lang.Override
    public int getMatchDuration() {
      return matchDuration_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getMatchDate());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, matchDuration_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMatchDate());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, matchDuration_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.java_out.VideoGame.Match)) {
        return super.equals(obj);
      }
      org.example.java_out.VideoGame.Match other = (org.example.java_out.VideoGame.Match) obj;

      if (hasMatchDate() != other.hasMatchDate()) return false;
      if (hasMatchDate()) {
        if (!getMatchDate()
            .equals(other.getMatchDate())) return false;
      }
      if (hasMatchDuration() != other.hasMatchDuration()) return false;
      if (hasMatchDuration()) {
        if (getMatchDuration()
            != other.getMatchDuration()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMatchDate()) {
        hash = (37 * hash) + MATCHDATE_FIELD_NUMBER;
        hash = (53 * hash) + getMatchDate().hashCode();
      }
      if (hasMatchDuration()) {
        hash = (37 * hash) + MATCHDURATION_FIELD_NUMBER;
        hash = (53 * hash) + getMatchDuration();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.java_out.VideoGame.Match parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.java_out.VideoGame.Match parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.java_out.VideoGame.Match parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.java_out.VideoGame.Match parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.java_out.VideoGame.Match prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.VideoGame.Match}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.VideoGame.Match)
        org.example.java_out.VideoGame.MatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_Match_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_Match_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.java_out.VideoGame.Match.class, org.example.java_out.VideoGame.Match.Builder.class);
      }

      // Construct using org.example.java_out.VideoGame.Match.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getMatchDateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        matchDate_ = null;
        if (matchDateBuilder_ != null) {
          matchDateBuilder_.dispose();
          matchDateBuilder_ = null;
        }
        matchDuration_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_Match_descriptor;
      }

      @java.lang.Override
      public org.example.java_out.VideoGame.Match getDefaultInstanceForType() {
        return org.example.java_out.VideoGame.Match.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.java_out.VideoGame.Match build() {
        org.example.java_out.VideoGame.Match result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.java_out.VideoGame.Match buildPartial() {
        org.example.java_out.VideoGame.Match result = new org.example.java_out.VideoGame.Match(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.java_out.VideoGame.Match result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.matchDate_ = matchDateBuilder_ == null
              ? matchDate_
              : matchDateBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.matchDuration_ = matchDuration_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.java_out.VideoGame.Match) {
          return mergeFrom((org.example.java_out.VideoGame.Match)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.java_out.VideoGame.Match other) {
        if (other == org.example.java_out.VideoGame.Match.getDefaultInstance()) return this;
        if (other.hasMatchDate()) {
          mergeMatchDate(other.getMatchDate());
        }
        if (other.hasMatchDuration()) {
          setMatchDuration(other.getMatchDuration());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMatchDateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                matchDuration_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private org.example.java_out.Date matchDate_;
      private com.google.protobuf.SingleFieldBuilder<
          org.example.java_out.Date, org.example.java_out.Date.Builder, org.example.java_out.DateOrBuilder> matchDateBuilder_;
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       * @return Whether the matchDate field is set.
       */
      public boolean hasMatchDate() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       * @return The matchDate.
       */
      public org.example.java_out.Date getMatchDate() {
        if (matchDateBuilder_ == null) {
          return matchDate_ == null ? org.example.java_out.Date.getDefaultInstance() : matchDate_;
        } else {
          return matchDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       */
      public Builder setMatchDate(org.example.java_out.Date value) {
        if (matchDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          matchDate_ = value;
        } else {
          matchDateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       */
      public Builder setMatchDate(
          org.example.java_out.Date.Builder builderForValue) {
        if (matchDateBuilder_ == null) {
          matchDate_ = builderForValue.build();
        } else {
          matchDateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       */
      public Builder mergeMatchDate(org.example.java_out.Date value) {
        if (matchDateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            matchDate_ != null &&
            matchDate_ != org.example.java_out.Date.getDefaultInstance()) {
            getMatchDateBuilder().mergeFrom(value);
          } else {
            matchDate_ = value;
          }
        } else {
          matchDateBuilder_.mergeFrom(value);
        }
        if (matchDate_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       */
      public Builder clearMatchDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        matchDate_ = null;
        if (matchDateBuilder_ != null) {
          matchDateBuilder_.dispose();
          matchDateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       */
      public org.example.java_out.Date.Builder getMatchDateBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMatchDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       */
      public org.example.java_out.DateOrBuilder getMatchDateOrBuilder() {
        if (matchDateBuilder_ != null) {
          return matchDateBuilder_.getMessageOrBuilder();
        } else {
          return matchDate_ == null ?
              org.example.java_out.Date.getDefaultInstance() : matchDate_;
        }
      }
      /**
       * <code>.org.example.Date matchDate = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.example.java_out.Date, org.example.java_out.Date.Builder, org.example.java_out.DateOrBuilder> 
          getMatchDateFieldBuilder() {
        if (matchDateBuilder_ == null) {
          matchDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.example.java_out.Date, org.example.java_out.Date.Builder, org.example.java_out.DateOrBuilder>(
                  getMatchDate(),
                  getParentForChildren(),
                  isClean());
          matchDate_ = null;
        }
        return matchDateBuilder_;
      }

      private int matchDuration_ ;
      /**
       * <code>optional int32 matchDuration = 2;</code>
       * @return Whether the matchDuration field is set.
       */
      @java.lang.Override
      public boolean hasMatchDuration() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 matchDuration = 2;</code>
       * @return The matchDuration.
       */
      @java.lang.Override
      public int getMatchDuration() {
        return matchDuration_;
      }
      /**
       * <code>optional int32 matchDuration = 2;</code>
       * @param value The matchDuration to set.
       * @return This builder for chaining.
       */
      public Builder setMatchDuration(int value) {

        matchDuration_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 matchDuration = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMatchDuration() {
        bitField0_ = (bitField0_ & ~0x00000002);
        matchDuration_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.VideoGame.Match)
    }

    // @@protoc_insertion_point(class_scope:org.example.VideoGame.Match)
    private static final org.example.java_out.VideoGame.Match DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.java_out.VideoGame.Match();
    }

    public static org.example.java_out.VideoGame.Match getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Match>
        PARSER = new com.google.protobuf.AbstractParser<Match>() {
      @java.lang.Override
      public Match parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Match> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Match> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.java_out.VideoGame.Match getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Name of the game
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the game
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_ = 0;
  /**
   * <pre>
   * Type of the game (default is GENERIC)
   * </pre>
   *
   * <code>.org.example.VideoGame.GameType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Type of the game (default is GENERIC)
   * </pre>
   *
   * <code>.org.example.VideoGame.GameType type = 2;</code>
   * @return The type.
   */
  @java.lang.Override public org.example.java_out.VideoGame.GameType getType() {
    org.example.java_out.VideoGame.GameType result = org.example.java_out.VideoGame.GameType.forNumber(type_);
    return result == null ? org.example.java_out.VideoGame.GameType.UNRECOGNIZED : result;
  }

  public static final int RELEASEDATE_FIELD_NUMBER = 3;
  private org.example.java_out.Date releaseDate_;
  /**
   * <pre>
   * Release date of the game in the GameReleaseDate format created above
   * </pre>
   *
   * <code>.org.example.Date releaseDate = 3;</code>
   * @return Whether the releaseDate field is set.
   */
  @java.lang.Override
  public boolean hasReleaseDate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Release date of the game in the GameReleaseDate format created above
   * </pre>
   *
   * <code>.org.example.Date releaseDate = 3;</code>
   * @return The releaseDate.
   */
  @java.lang.Override
  public org.example.java_out.Date getReleaseDate() {
    return releaseDate_ == null ? org.example.java_out.Date.getDefaultInstance() : releaseDate_;
  }
  /**
   * <pre>
   * Release date of the game in the GameReleaseDate format created above
   * </pre>
   *
   * <code>.org.example.Date releaseDate = 3;</code>
   */
  @java.lang.Override
  public org.example.java_out.DateOrBuilder getReleaseDateOrBuilder() {
    return releaseDate_ == null ? org.example.java_out.Date.getDefaultInstance() : releaseDate_;
  }

  public static final int MATCHPLAYED_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<org.example.java_out.VideoGame.Match> matchPlayed_;
  /**
   * <pre>
   * List of match played
   * </pre>
   *
   * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.java_out.VideoGame.Match> getMatchPlayedList() {
    return matchPlayed_;
  }
  /**
   * <pre>
   * List of match played
   * </pre>
   *
   * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.java_out.VideoGame.MatchOrBuilder> 
      getMatchPlayedOrBuilderList() {
    return matchPlayed_;
  }
  /**
   * <pre>
   * List of match played
   * </pre>
   *
   * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
   */
  @java.lang.Override
  public int getMatchPlayedCount() {
    return matchPlayed_.size();
  }
  /**
   * <pre>
   * List of match played
   * </pre>
   *
   * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
   */
  @java.lang.Override
  public org.example.java_out.VideoGame.Match getMatchPlayed(int index) {
    return matchPlayed_.get(index);
  }
  /**
   * <pre>
   * List of match played
   * </pre>
   *
   * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
   */
  @java.lang.Override
  public org.example.java_out.VideoGame.MatchOrBuilder getMatchPlayedOrBuilder(
      int index) {
    return matchPlayed_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (type_ != org.example.java_out.VideoGame.GameType.GENERIC.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getReleaseDate());
    }
    for (int i = 0; i < matchPlayed_.size(); i++) {
      output.writeMessage(4, matchPlayed_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (type_ != org.example.java_out.VideoGame.GameType.GENERIC.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getReleaseDate());
    }
    for (int i = 0; i < matchPlayed_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, matchPlayed_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.java_out.VideoGame)) {
      return super.equals(obj);
    }
    org.example.java_out.VideoGame other = (org.example.java_out.VideoGame) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (type_ != other.type_) return false;
    if (hasReleaseDate() != other.hasReleaseDate()) return false;
    if (hasReleaseDate()) {
      if (!getReleaseDate()
          .equals(other.getReleaseDate())) return false;
    }
    if (!getMatchPlayedList()
        .equals(other.getMatchPlayedList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasReleaseDate()) {
      hash = (37 * hash) + RELEASEDATE_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseDate().hashCode();
    }
    if (getMatchPlayedCount() > 0) {
      hash = (37 * hash) + MATCHPLAYED_FIELD_NUMBER;
      hash = (53 * hash) + getMatchPlayedList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.java_out.VideoGame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.java_out.VideoGame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.java_out.VideoGame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.java_out.VideoGame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.java_out.VideoGame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.java_out.VideoGame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.java_out.VideoGame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.java_out.VideoGame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.java_out.VideoGame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.java_out.VideoGame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.java_out.VideoGame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.java_out.VideoGame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.java_out.VideoGame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.VideoGame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.VideoGame)
      org.example.java_out.VideoGameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.java_out.VideoGame.class, org.example.java_out.VideoGame.Builder.class);
    }

    // Construct using org.example.java_out.VideoGame.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getReleaseDateFieldBuilder();
        getMatchPlayedFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      type_ = 0;
      releaseDate_ = null;
      if (releaseDateBuilder_ != null) {
        releaseDateBuilder_.dispose();
        releaseDateBuilder_ = null;
      }
      if (matchPlayedBuilder_ == null) {
        matchPlayed_ = java.util.Collections.emptyList();
      } else {
        matchPlayed_ = null;
        matchPlayedBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGame_descriptor;
    }

    @java.lang.Override
    public org.example.java_out.VideoGame getDefaultInstanceForType() {
      return org.example.java_out.VideoGame.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.java_out.VideoGame build() {
      org.example.java_out.VideoGame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.java_out.VideoGame buildPartial() {
      org.example.java_out.VideoGame result = new org.example.java_out.VideoGame(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.java_out.VideoGame result) {
      if (matchPlayedBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          matchPlayed_ = java.util.Collections.unmodifiableList(matchPlayed_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.matchPlayed_ = matchPlayed_;
      } else {
        result.matchPlayed_ = matchPlayedBuilder_.build();
      }
    }

    private void buildPartial0(org.example.java_out.VideoGame result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.releaseDate_ = releaseDateBuilder_ == null
            ? releaseDate_
            : releaseDateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.java_out.VideoGame) {
        return mergeFrom((org.example.java_out.VideoGame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.java_out.VideoGame other) {
      if (other == org.example.java_out.VideoGame.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasReleaseDate()) {
        mergeReleaseDate(other.getReleaseDate());
      }
      if (matchPlayedBuilder_ == null) {
        if (!other.matchPlayed_.isEmpty()) {
          if (matchPlayed_.isEmpty()) {
            matchPlayed_ = other.matchPlayed_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMatchPlayedIsMutable();
            matchPlayed_.addAll(other.matchPlayed_);
          }
          onChanged();
        }
      } else {
        if (!other.matchPlayed_.isEmpty()) {
          if (matchPlayedBuilder_.isEmpty()) {
            matchPlayedBuilder_.dispose();
            matchPlayedBuilder_ = null;
            matchPlayed_ = other.matchPlayed_;
            bitField0_ = (bitField0_ & ~0x00000008);
            matchPlayedBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getMatchPlayedFieldBuilder() : null;
          } else {
            matchPlayedBuilder_.addAllMessages(other.matchPlayed_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getReleaseDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              org.example.java_out.VideoGame.Match m =
                  input.readMessage(
                      org.example.java_out.VideoGame.Match.parser(),
                      extensionRegistry);
              if (matchPlayedBuilder_ == null) {
                ensureMatchPlayedIsMutable();
                matchPlayed_.add(m);
              } else {
                matchPlayedBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the game
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the game
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the game
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the game
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the game
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * Type of the game (default is GENERIC)
     * </pre>
     *
     * <code>.org.example.VideoGame.GameType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Type of the game (default is GENERIC)
     * </pre>
     *
     * <code>.org.example.VideoGame.GameType type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the game (default is GENERIC)
     * </pre>
     *
     * <code>.org.example.VideoGame.GameType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public org.example.java_out.VideoGame.GameType getType() {
      org.example.java_out.VideoGame.GameType result = org.example.java_out.VideoGame.GameType.forNumber(type_);
      return result == null ? org.example.java_out.VideoGame.GameType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Type of the game (default is GENERIC)
     * </pre>
     *
     * <code>.org.example.VideoGame.GameType type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(org.example.java_out.VideoGame.GameType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the game (default is GENERIC)
     * </pre>
     *
     * <code>.org.example.VideoGame.GameType type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private org.example.java_out.Date releaseDate_;
    private com.google.protobuf.SingleFieldBuilder<
        org.example.java_out.Date, org.example.java_out.Date.Builder, org.example.java_out.DateOrBuilder> releaseDateBuilder_;
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     * @return Whether the releaseDate field is set.
     */
    public boolean hasReleaseDate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     * @return The releaseDate.
     */
    public org.example.java_out.Date getReleaseDate() {
      if (releaseDateBuilder_ == null) {
        return releaseDate_ == null ? org.example.java_out.Date.getDefaultInstance() : releaseDate_;
      } else {
        return releaseDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     */
    public Builder setReleaseDate(org.example.java_out.Date value) {
      if (releaseDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        releaseDate_ = value;
      } else {
        releaseDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     */
    public Builder setReleaseDate(
        org.example.java_out.Date.Builder builderForValue) {
      if (releaseDateBuilder_ == null) {
        releaseDate_ = builderForValue.build();
      } else {
        releaseDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     */
    public Builder mergeReleaseDate(org.example.java_out.Date value) {
      if (releaseDateBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          releaseDate_ != null &&
          releaseDate_ != org.example.java_out.Date.getDefaultInstance()) {
          getReleaseDateBuilder().mergeFrom(value);
        } else {
          releaseDate_ = value;
        }
      } else {
        releaseDateBuilder_.mergeFrom(value);
      }
      if (releaseDate_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     */
    public Builder clearReleaseDate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      releaseDate_ = null;
      if (releaseDateBuilder_ != null) {
        releaseDateBuilder_.dispose();
        releaseDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     */
    public org.example.java_out.Date.Builder getReleaseDateBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getReleaseDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     */
    public org.example.java_out.DateOrBuilder getReleaseDateOrBuilder() {
      if (releaseDateBuilder_ != null) {
        return releaseDateBuilder_.getMessageOrBuilder();
      } else {
        return releaseDate_ == null ?
            org.example.java_out.Date.getDefaultInstance() : releaseDate_;
      }
    }
    /**
     * <pre>
     * Release date of the game in the GameReleaseDate format created above
     * </pre>
     *
     * <code>.org.example.Date releaseDate = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.example.java_out.Date, org.example.java_out.Date.Builder, org.example.java_out.DateOrBuilder> 
        getReleaseDateFieldBuilder() {
      if (releaseDateBuilder_ == null) {
        releaseDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.example.java_out.Date, org.example.java_out.Date.Builder, org.example.java_out.DateOrBuilder>(
                getReleaseDate(),
                getParentForChildren(),
                isClean());
        releaseDate_ = null;
      }
      return releaseDateBuilder_;
    }

    private java.util.List<org.example.java_out.VideoGame.Match> matchPlayed_ =
      java.util.Collections.emptyList();
    private void ensureMatchPlayedIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        matchPlayed_ = new java.util.ArrayList<org.example.java_out.VideoGame.Match>(matchPlayed_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.java_out.VideoGame.Match, org.example.java_out.VideoGame.Match.Builder, org.example.java_out.VideoGame.MatchOrBuilder> matchPlayedBuilder_;

    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public java.util.List<org.example.java_out.VideoGame.Match> getMatchPlayedList() {
      if (matchPlayedBuilder_ == null) {
        return java.util.Collections.unmodifiableList(matchPlayed_);
      } else {
        return matchPlayedBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public int getMatchPlayedCount() {
      if (matchPlayedBuilder_ == null) {
        return matchPlayed_.size();
      } else {
        return matchPlayedBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public org.example.java_out.VideoGame.Match getMatchPlayed(int index) {
      if (matchPlayedBuilder_ == null) {
        return matchPlayed_.get(index);
      } else {
        return matchPlayedBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder setMatchPlayed(
        int index, org.example.java_out.VideoGame.Match value) {
      if (matchPlayedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchPlayedIsMutable();
        matchPlayed_.set(index, value);
        onChanged();
      } else {
        matchPlayedBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder setMatchPlayed(
        int index, org.example.java_out.VideoGame.Match.Builder builderForValue) {
      if (matchPlayedBuilder_ == null) {
        ensureMatchPlayedIsMutable();
        matchPlayed_.set(index, builderForValue.build());
        onChanged();
      } else {
        matchPlayedBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder addMatchPlayed(org.example.java_out.VideoGame.Match value) {
      if (matchPlayedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchPlayedIsMutable();
        matchPlayed_.add(value);
        onChanged();
      } else {
        matchPlayedBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder addMatchPlayed(
        int index, org.example.java_out.VideoGame.Match value) {
      if (matchPlayedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatchPlayedIsMutable();
        matchPlayed_.add(index, value);
        onChanged();
      } else {
        matchPlayedBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder addMatchPlayed(
        org.example.java_out.VideoGame.Match.Builder builderForValue) {
      if (matchPlayedBuilder_ == null) {
        ensureMatchPlayedIsMutable();
        matchPlayed_.add(builderForValue.build());
        onChanged();
      } else {
        matchPlayedBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder addMatchPlayed(
        int index, org.example.java_out.VideoGame.Match.Builder builderForValue) {
      if (matchPlayedBuilder_ == null) {
        ensureMatchPlayedIsMutable();
        matchPlayed_.add(index, builderForValue.build());
        onChanged();
      } else {
        matchPlayedBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder addAllMatchPlayed(
        java.lang.Iterable<? extends org.example.java_out.VideoGame.Match> values) {
      if (matchPlayedBuilder_ == null) {
        ensureMatchPlayedIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, matchPlayed_);
        onChanged();
      } else {
        matchPlayedBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder clearMatchPlayed() {
      if (matchPlayedBuilder_ == null) {
        matchPlayed_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        matchPlayedBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public Builder removeMatchPlayed(int index) {
      if (matchPlayedBuilder_ == null) {
        ensureMatchPlayedIsMutable();
        matchPlayed_.remove(index);
        onChanged();
      } else {
        matchPlayedBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public org.example.java_out.VideoGame.Match.Builder getMatchPlayedBuilder(
        int index) {
      return getMatchPlayedFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public org.example.java_out.VideoGame.MatchOrBuilder getMatchPlayedOrBuilder(
        int index) {
      if (matchPlayedBuilder_ == null) {
        return matchPlayed_.get(index);  } else {
        return matchPlayedBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public java.util.List<? extends org.example.java_out.VideoGame.MatchOrBuilder> 
         getMatchPlayedOrBuilderList() {
      if (matchPlayedBuilder_ != null) {
        return matchPlayedBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(matchPlayed_);
      }
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public org.example.java_out.VideoGame.Match.Builder addMatchPlayedBuilder() {
      return getMatchPlayedFieldBuilder().addBuilder(
          org.example.java_out.VideoGame.Match.getDefaultInstance());
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public org.example.java_out.VideoGame.Match.Builder addMatchPlayedBuilder(
        int index) {
      return getMatchPlayedFieldBuilder().addBuilder(
          index, org.example.java_out.VideoGame.Match.getDefaultInstance());
    }
    /**
     * <pre>
     * List of match played
     * </pre>
     *
     * <code>repeated .org.example.VideoGame.Match matchPlayed = 4;</code>
     */
    public java.util.List<org.example.java_out.VideoGame.Match.Builder> 
         getMatchPlayedBuilderList() {
      return getMatchPlayedFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.java_out.VideoGame.Match, org.example.java_out.VideoGame.Match.Builder, org.example.java_out.VideoGame.MatchOrBuilder> 
        getMatchPlayedFieldBuilder() {
      if (matchPlayedBuilder_ == null) {
        matchPlayedBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.example.java_out.VideoGame.Match, org.example.java_out.VideoGame.Match.Builder, org.example.java_out.VideoGame.MatchOrBuilder>(
                matchPlayed_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        matchPlayed_ = null;
      }
      return matchPlayedBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.example.VideoGame)
  }

  // @@protoc_insertion_point(class_scope:org.example.VideoGame)
  private static final org.example.java_out.VideoGame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.java_out.VideoGame();
  }

  public static org.example.java_out.VideoGame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VideoGame>
      PARSER = new com.google.protobuf.AbstractParser<VideoGame>() {
    @java.lang.Override
    public VideoGame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VideoGame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VideoGame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.java_out.VideoGame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

