// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoGames.proto

// Protobuf Java Version: 4.26.0-rc2
package org.example.java_out;

/**
 * Protobuf type {@code org.example.VideoGameLibrary}
 */
public final class VideoGameLibrary extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.example.VideoGameLibrary)
    VideoGameLibraryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "-rc2",
      VideoGameLibrary.class.getName());
  }
  // Use VideoGameLibrary.newBuilder() to construct.
  private VideoGameLibrary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VideoGameLibrary() {
    game_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGameLibrary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGameLibrary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.java_out.VideoGameLibrary.class, org.example.java_out.VideoGameLibrary.Builder.class);
  }

  public static final int GAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.example.java_out.VideoGame> game_;
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.java_out.VideoGame> getGameList() {
    return game_;
  }
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.java_out.VideoGameOrBuilder> 
      getGameOrBuilderList() {
    return game_;
  }
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  @java.lang.Override
  public int getGameCount() {
    return game_.size();
  }
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  @java.lang.Override
  public org.example.java_out.VideoGame getGame(int index) {
    return game_.get(index);
  }
  /**
   * <pre>
   * List of games in the library
   * </pre>
   *
   * <code>repeated .org.example.VideoGame game = 1;</code>
   */
  @java.lang.Override
  public org.example.java_out.VideoGameOrBuilder getGameOrBuilder(
      int index) {
    return game_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < game_.size(); i++) {
      output.writeMessage(1, game_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < game_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, game_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.java_out.VideoGameLibrary)) {
      return super.equals(obj);
    }
    org.example.java_out.VideoGameLibrary other = (org.example.java_out.VideoGameLibrary) obj;

    if (!getGameList()
        .equals(other.getGameList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGameCount() > 0) {
      hash = (37 * hash) + GAME_FIELD_NUMBER;
      hash = (53 * hash) + getGameList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.java_out.VideoGameLibrary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.java_out.VideoGameLibrary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.java_out.VideoGameLibrary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.java_out.VideoGameLibrary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.java_out.VideoGameLibrary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.example.VideoGameLibrary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.example.VideoGameLibrary)
      org.example.java_out.VideoGameLibraryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGameLibrary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGameLibrary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.java_out.VideoGameLibrary.class, org.example.java_out.VideoGameLibrary.Builder.class);
    }

    // Construct using org.example.java_out.VideoGameLibrary.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (gameBuilder_ == null) {
        game_ = java.util.Collections.emptyList();
      } else {
        game_ = null;
        gameBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.java_out.VideoGamesProto.internal_static_org_example_VideoGameLibrary_descriptor;
    }

    @java.lang.Override
    public org.example.java_out.VideoGameLibrary getDefaultInstanceForType() {
      return org.example.java_out.VideoGameLibrary.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.java_out.VideoGameLibrary build() {
      org.example.java_out.VideoGameLibrary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.java_out.VideoGameLibrary buildPartial() {
      org.example.java_out.VideoGameLibrary result = new org.example.java_out.VideoGameLibrary(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.java_out.VideoGameLibrary result) {
      if (gameBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          game_ = java.util.Collections.unmodifiableList(game_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.game_ = game_;
      } else {
        result.game_ = gameBuilder_.build();
      }
    }

    private void buildPartial0(org.example.java_out.VideoGameLibrary result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.java_out.VideoGameLibrary) {
        return mergeFrom((org.example.java_out.VideoGameLibrary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.java_out.VideoGameLibrary other) {
      if (other == org.example.java_out.VideoGameLibrary.getDefaultInstance()) return this;
      if (gameBuilder_ == null) {
        if (!other.game_.isEmpty()) {
          if (game_.isEmpty()) {
            game_ = other.game_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGameIsMutable();
            game_.addAll(other.game_);
          }
          onChanged();
        }
      } else {
        if (!other.game_.isEmpty()) {
          if (gameBuilder_.isEmpty()) {
            gameBuilder_.dispose();
            gameBuilder_ = null;
            game_ = other.game_;
            bitField0_ = (bitField0_ & ~0x00000001);
            gameBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getGameFieldBuilder() : null;
          } else {
            gameBuilder_.addAllMessages(other.game_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.example.java_out.VideoGame m =
                  input.readMessage(
                      org.example.java_out.VideoGame.parser(),
                      extensionRegistry);
              if (gameBuilder_ == null) {
                ensureGameIsMutable();
                game_.add(m);
              } else {
                gameBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.example.java_out.VideoGame> game_ =
      java.util.Collections.emptyList();
    private void ensureGameIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        game_ = new java.util.ArrayList<org.example.java_out.VideoGame>(game_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.java_out.VideoGame, org.example.java_out.VideoGame.Builder, org.example.java_out.VideoGameOrBuilder> gameBuilder_;

    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public java.util.List<org.example.java_out.VideoGame> getGameList() {
      if (gameBuilder_ == null) {
        return java.util.Collections.unmodifiableList(game_);
      } else {
        return gameBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public int getGameCount() {
      if (gameBuilder_ == null) {
        return game_.size();
      } else {
        return gameBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public org.example.java_out.VideoGame getGame(int index) {
      if (gameBuilder_ == null) {
        return game_.get(index);
      } else {
        return gameBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder setGame(
        int index, org.example.java_out.VideoGame value) {
      if (gameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGameIsMutable();
        game_.set(index, value);
        onChanged();
      } else {
        gameBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder setGame(
        int index, org.example.java_out.VideoGame.Builder builderForValue) {
      if (gameBuilder_ == null) {
        ensureGameIsMutable();
        game_.set(index, builderForValue.build());
        onChanged();
      } else {
        gameBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder addGame(org.example.java_out.VideoGame value) {
      if (gameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGameIsMutable();
        game_.add(value);
        onChanged();
      } else {
        gameBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder addGame(
        int index, org.example.java_out.VideoGame value) {
      if (gameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGameIsMutable();
        game_.add(index, value);
        onChanged();
      } else {
        gameBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder addGame(
        org.example.java_out.VideoGame.Builder builderForValue) {
      if (gameBuilder_ == null) {
        ensureGameIsMutable();
        game_.add(builderForValue.build());
        onChanged();
      } else {
        gameBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder addGame(
        int index, org.example.java_out.VideoGame.Builder builderForValue) {
      if (gameBuilder_ == null) {
        ensureGameIsMutable();
        game_.add(index, builderForValue.build());
        onChanged();
      } else {
        gameBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder addAllGame(
        java.lang.Iterable<? extends org.example.java_out.VideoGame> values) {
      if (gameBuilder_ == null) {
        ensureGameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, game_);
        onChanged();
      } else {
        gameBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder clearGame() {
      if (gameBuilder_ == null) {
        game_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        gameBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public Builder removeGame(int index) {
      if (gameBuilder_ == null) {
        ensureGameIsMutable();
        game_.remove(index);
        onChanged();
      } else {
        gameBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public org.example.java_out.VideoGame.Builder getGameBuilder(
        int index) {
      return getGameFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public org.example.java_out.VideoGameOrBuilder getGameOrBuilder(
        int index) {
      if (gameBuilder_ == null) {
        return game_.get(index);  } else {
        return gameBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public java.util.List<? extends org.example.java_out.VideoGameOrBuilder> 
         getGameOrBuilderList() {
      if (gameBuilder_ != null) {
        return gameBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(game_);
      }
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public org.example.java_out.VideoGame.Builder addGameBuilder() {
      return getGameFieldBuilder().addBuilder(
          org.example.java_out.VideoGame.getDefaultInstance());
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public org.example.java_out.VideoGame.Builder addGameBuilder(
        int index) {
      return getGameFieldBuilder().addBuilder(
          index, org.example.java_out.VideoGame.getDefaultInstance());
    }
    /**
     * <pre>
     * List of games in the library
     * </pre>
     *
     * <code>repeated .org.example.VideoGame game = 1;</code>
     */
    public java.util.List<org.example.java_out.VideoGame.Builder> 
         getGameBuilderList() {
      return getGameFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.example.java_out.VideoGame, org.example.java_out.VideoGame.Builder, org.example.java_out.VideoGameOrBuilder> 
        getGameFieldBuilder() {
      if (gameBuilder_ == null) {
        gameBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.example.java_out.VideoGame, org.example.java_out.VideoGame.Builder, org.example.java_out.VideoGameOrBuilder>(
                game_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        game_ = null;
      }
      return gameBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.example.VideoGameLibrary)
  }

  // @@protoc_insertion_point(class_scope:org.example.VideoGameLibrary)
  private static final org.example.java_out.VideoGameLibrary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.java_out.VideoGameLibrary();
  }

  public static org.example.java_out.VideoGameLibrary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VideoGameLibrary>
      PARSER = new com.google.protobuf.AbstractParser<VideoGameLibrary>() {
    @java.lang.Override
    public VideoGameLibrary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VideoGameLibrary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VideoGameLibrary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.java_out.VideoGameLibrary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

